### ISSUE TITLE
Error("data did not match any variant of untagged enum QuoteResponse",

### ISSUE THREAD

**Issue by mugncuphelp** [maksimryndin/ekubo-atomic-arbitrage#3]
hello, i'm getting this error when trying to run yur code. i have tried to solve it myself, but all i manage to do is pinpoint that the funtion quotes() in ekubo::lib.rs failed to return Result<models::Quotes>. i might be wrong in this thought.

```
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.27s
     Running `target\debug\ekubo-atomic-arbitrage.exe simple`
2024-10-05T19:27:26.748543Z  INFO ekubo_atomic_arbitrage: starting bot with Ekubo API https://sepolia-api.ekubo.org and RPC https://free-rpc.nethermind.io/sepolia-juno/v0_7, strategy: Simple
2024-10-05T19:27:27.510000Z  INFO ekubo_atomic_arbitrage: Account balance: 25000000000000000 WEI
2024-10-05T19:27:30.942377Z ERROR ekubo_atomic_arbitrage: quotes err: Serde(
    Error("data did not match any variant of untagged enum QuoteResponse", line: 0, column: 0),
)
2024-10-05T19:27:31.046781Z ERROR ekubo_atomic_arbitrage: quotes err: Serde(
    Error("data did not match any variant of untagged enum QuoteResponse", line: 0, column: 0),
)
error: process didn't exit successfully: `target\debug\ekubo-atomic-arbitrage.exe simple` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```

**Comment by maksimryndin** [comment]
Hey! :) Thanks for reading and reaching out! You're right. The issue is that Ekubo API has changed (and be ready that many things in Starknet are under active developments so some code and procedures will require updates).

I've pushed the necessary change https://github.com/maksimryndin/ekubo-atomic-arbitrage/commit/26251d81d8add9805b600382ac2ac235da5bbdae#diff-7f92d7e6d5b180d7d4c070ff32d74024cc680fa27e937008e28e201d9c8a116a

**Comment by mugncuphelp** [comment]
thanks for fixing the bug. i appreciate it. the code works now.
